
services:
  mysql:
    image: mysql:8.0
    container_name: betalent_mysql
    environment:
      MYSQL_ROOT_PASSWORD: betalent123
      MYSQL_DATABASE: betalent
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      --default-authentication-plugin=mysql_native_password
      --bind-address=0.0.0.0
      --skip-host-cache
      --skip-name-resolve
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pbetalent123"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
