
CREATE DATABASE IF NOT EXISTS betalent;
ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'betalent123';
CREATE USER IF NOT EXISTS 'root'@'localhost' IDENTIFIED BY 'betalent123';
CREATE USER IF NOT EXISTS 'root'@'172.18.0.1' IDENTIFIED BY 'betalent123';
CREATE USER IF NOT EXISTS 'root'@'172.18.0.2' IDENTIFIED BY 'betalent123';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'172.18.0.1' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'172.18.0.2' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
